@startuml
Actor -> Bootstrap: Bootstraping Dubbo Provider
Bootstrap -> ServiceBean: Authentication Response
ServiceBean -> ServiceConfig: export()
ServiceConfig -> ServiceConfig: doExport()
ServiceConfig -> ServiceConfig: doExportUrls()
ServiceConfig -> ServiceConfig: doExportUrlsFor1Protocol()
alt local[Injvm]
ServiceConfig -> ServiceConfig: exportLocal()
ProtocolAdaptive -> InjvmProtocol: export()
InjvmProtocol -> InjvmExporter: new InjvmExporter()
else remote[Dubbo]
ServiceConfig -> ProtocolAdaptive: export()
ProtocolAdaptive -> DubboProtocol: export()
end
DubboProtocol -> DubboProtocol: openServer()
DubboProtocol -> DubboProtocol: createServer()
DubboProtocol -> Exchangers: bind()
Exchangers -> Exchangers: bind()
Exchangers -> Exchangers: getExchanger()
Exchangers -> HeaderExchanger: bind()
HeaderExchanger -> HeaderExchangerServer: new HeaderExchangerServer()
HeaderExchangerServer -> Transporters: bind()
Transporters -> Transporters: getTransporter()
Transporters -> TransporterAdaptive: bind()
TransporterAdaptive -> NettyTransporter: Dubbo SPI
NettyTransporter -> NettyServer: new NettyServer()
NettyServer -> AbstractServer: doOpen()
@enduml