#language: java
#jdk:
#  - oraclejdk8
#
#before_install:
#  - pip install --user codecov
#after_success:
#  - codecov
#
#script: "mvn cobertura:cobertura"
#
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
language: java
sudo: false # faster builds

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)