spring:
  application:
    name: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    hostname: localhost
server:
  port: 1112
swagger:
  base-package: cn.shuaijunlan
