spring:
  application:
    name: trace-2
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 0.1
server:
  port: 9102
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

