spring:
  application:
    name: trace-1
  zipkin:
      base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 0.1
server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/